### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by haribole** [danielfrg/jupyterhub-kubernetes_spawner#2]
Hi Daniel

Thanks for posting this, I tried it out but keep getting an internal server error when I try to login with a user created in ldap. I tried getting a bash shell on the hub, but there is no response to the kubectl exec command.  Any ideas how I can troubleshoot this?

Thanks
Hari

**Comment by nguyenvanhoang7398** [comment]
I'm also having the same problem, please assist
